import { Bot, Heart, Menu, MessageSquare, Plus, Send, ShieldCheck, Trash2, X } from 'lucide-react'
import { useEffect, useRef, useState } from 'react'

const crisisWords = /bunuh diri|mengakhiri hidup|menyakiti diri|self.?harm|melukai diri|tidak ingin hidup/i
const replies = { Ringan: 'Terima kasih sudah bercerita. Perasaan yang naik-turun itu manusiawi. Mari pilih satu hal kecil yang bisa membuat hari ini terasa lebih ringan.', Sedang: 'Kedengarannya kamu sedang membawa cukup banyak beban. Kita tidak perlu menyelesaikan semuanya sekarang—boleh mulai dari satu napas perlahan atau satu orang yang aman untuk diajak bicara.', Tinggi: 'Terima kasih sudah mempercayai ruang ini. Beban yang kamu rasakan pantas didampingi. Jika memungkinkan, coba hubungi orang dewasa tepercaya atau psikolog agar kamu tidak menghadapinya sendiri.' }
const newChat = () => ({ id: `${Date.now()}-${Math.random()}`, title: 'Percakapan baru', updatedAt: Date.now(), messages: [] })
function responseFor(text, level) { if (crisisWords.test(text)) return 'Aku ikut prihatin kamu sedang merasakan hal seberat ini. Keselamatanmu penting: tolong segera hubungi orang dewasa yang kamu percaya, keluarga, atau teman yang bisa menemanimu sekarang. Jika kamu berada dalam bahaya langsung, hubungi layanan darurat setempat atau pergi ke fasilitas kesehatan terdekat. Kamu tidak harus melewati ini sendirian.'; if (/tenang|cemas|panik/i.test(text)) return 'Mari beri tubuhmu jeda singkat: tarik napas pelan selama 4 hitungan, lalu hembuskan selama 6 hitungan. Ulangi tiga kali. Setelah itu, ceritakan bagian mana yang terasa paling berat.'; if (/orang tua|keluarga/i.test(text)) return 'Memulai percakapan dengan keluarga memang tidak selalu mudah. Kamu bisa mencoba kalimat sederhana: “Aku ingin didengar dulu, bukan langsung dicari solusinya.” Apakah ada satu orang yang terasa paling aman untuk diajak bicara?'; return replies[level] || replies.Ringan }
function loadChats() { const saved = JSON.parse(localStorage.getItem('aegis-chat-conversations') || 'null'); if (Array.isArray(saved) && saved.length) return saved; const legacy = JSON.parse(localStorage.getItem('aegis-chat-history') || 'null'); const chat = newChat(); if (Array.isArray(legacy) && legacy.length) chat.messages = legacy; return [chat] }

export default function AiAssistant() {
  const saved = JSON.parse(localStorage.getItem('aegis-screening') || 'null'); const level = saved?.level?.label || 'Ringan'
  const [conversations, setConversations] = useState(() => loadChats()); const [activeId, setActiveId] = useState(() => loadChats()[0].id); const [text, setText] = useState(''); const [sidebarOpen, setSidebarOpen] = useState(false); const end = useRef(null)
  const active = conversations.find((chat) => chat.id === activeId) || conversations[0]
  useEffect(() => { localStorage.setItem('aegis-chat-conversations', JSON.stringify(conversations)); if (active) localStorage.setItem('aegis-chat-history', JSON.stringify(active.messages)); end.current?.scrollIntoView({ behavior: 'smooth' }) }, [conversations, active])
  function createChat() { const chat = newChat(); setConversations((list) => [chat, ...list]); setActiveId(chat.id); setText(''); setSidebarOpen(false) }
  function deleteChat(id) { setConversations((list) => { const next = list.filter((item) => item.id !== id); if (!next.length) { const fresh = newChat(); setActiveId(fresh.id); return [fresh] } if (id === activeId) setActiveId(next[0].id); return next }) }
  function updateMessages(id, update) { setConversations((list) => list.map((chat) => chat.id === id ? { ...chat, messages: update(chat.messages), updatedAt: Date.now() } : chat)) }
  async function send(value = text) { const clean = value.trim(); if (!clean || !active) return; const title = active.title === 'Percakapan baru' ? `${clean.slice(0, 37)}${clean.length > 37 ? '…' : ''}` : active.title; setConversations((list) => list.map((chat) => chat.id === active.id ? { ...chat, title, updatedAt: Date.now(), messages: [...chat.messages, { role: 'user', text: clean }, { role: 'bot', text: 'Aegis sedang menyiapkan respons…' }] } : chat)); setText(''); try { const response = await fetch('/api/ai', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ message: clean, level }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error); updateMessages(active.id, (items) => [...items.slice(0, -1), { role: 'bot', text: data.text }]) } catch { updateMessages(active.id, (items) => [...items.slice(0, -1), { role: 'bot', text: responseFor(clean, level) }]) } }
  return <main className="chat-page chatgpt-layout"><aside className={`chat-sidebar ${sidebarOpen ? 'mobile-open' : ''}`}><div className="sidebar-head"><a className="brand" href="#beranda"><span className="brand-mark"><ShieldCheck size={20} /></span><span>Aegis</span></a><button className="sidebar-close" onClick={() => setSidebarOpen(false)}><X size={19} /></button></div><button className="new-chat" onClick={createChat}><Plus size={18} /> Percakapan baru</button><p className="history-label">RIWAYAT PERCAKAPAN</p><div className="conversation-list">{conversations.slice().sort((a, b) => b.updatedAt - a.updatedAt).map((chat) => <div className={`conversation ${chat.id === active?.id ? 'active' : ''}`} key={chat.id}><button onClick={() => { setActiveId(chat.id); setSidebarOpen(false) }}><MessageSquare size={16} /><span>{chat.title}</span></button><button className="delete-chat" onClick={() => deleteChat(chat.id)} aria-label="Hapus percakapan"><Trash2 size={15} /></button></div>)}</div><div className="sidebar-foot"><Heart size={15} /> Ruang dukungan privat<br /><small>Riwayat tersimpan di perangkat ini</small></div></aside><section className="chat-main"><header className="chat-top"><button className="mobile-menu" onClick={() => setSidebarOpen(true)}><Menu size={21} /></button><div><b>Aegis AI Assistant</b><span><i /> Gemini AI siap</span></div><a href="#beranda">Kembali</a></header><section className="chat-shell"><div className="chat-title compact"><span className="quiz-eyebrow"><Bot size={16} /> Dukungan emosional awal</span><h1>Apa yang sedang<br />kamu rasakan?</h1></div><div className="chat-disclaimer"><Heart size={16} /> AI ini memberikan pertolongan emosional awal dan bukan diagnosis medis final.</div><div className="messages">{active?.messages.length ? active.messages.map((message, i) => <div className={`bubble ${message.role}`} key={i}>{message.role === 'bot' && <Bot size={16} />}{message.text}</div>) : <div className="empty-chat"><Bot size={26} /><b>Percakapan baru dimulai</b><span>Ceritakan apa yang sedang ada di pikiranmu.</span></div>}<div ref={end} /></div><div className="suggestions">{['Aku lagi merasa kewalahan', 'Bantu aku tenang sebentar', 'Aku ingin bicara dengan orang tua'].map((item) => <button key={item} onClick={() => send(item)}>{item}</button>)}</div><form className="chat-input" onSubmit={(event) => { event.preventDefault(); send() }}><input value={text} onChange={(event) => setText(event.target.value)} placeholder="Tulis yang ingin kamu ceritakan…" /><button aria-label="Kirim"><Send size={18} /></button></form><p className="chat-footer-note">Aegis dapat keliru. Untuk situasi darurat, segera hubungi orang tepercaya atau layanan kesehatan terdekat.</p></section></section></main>
}
