import { ArrowLeft, CalendarDays, Check, ChevronRight, LockKeyhole, MapPin, ShieldCheck, Star, Video } from 'lucide-react'
import { useEffect, useState } from 'react'
import { psychologists } from '../data/psychologists'
function aliasFor() { let a = localStorage.getItem('aegis-user-alias'); if (!a) { a = `Keluarga-${String(Math.floor(100 + Math.random() * 900)).replace(/^/, 'A')}`; localStorage.setItem('aegis-user-alias', a) } return a }
export default function Counseling() {
  const [alias, setAlias] = useState(''); const [selected, setSelected] = useState(null); const [slot, setSlot] = useState(''); const [mode, setMode] = useState(''); const [note, setNote] = useState(''); const [confirmed, setConfirmed] = useState(null)
  useEffect(() => setAlias(aliasFor()), [])
  function choose(p) { setSelected(p); setSlot(''); setMode(p.mode === 'Hybrid' ? 'Online' : p.mode) }
  function book() { const item = { id: Date.now(), alias, psychologist: selected.name, slot, mode, note, status: 'Menunggu konfirmasi' }; const current = JSON.parse(localStorage.getItem('aegis-bookings') || '[]'); localStorage.setItem('aegis-bookings', JSON.stringify([...current, item])); setConfirmed(item) }
  if (confirmed) return <main className="counsel-page"><header className="quiz-topbar"><a className="brand" href="#beranda"><span className="brand-mark"><ShieldCheck size={22} /></span><span>Aegis</span></a></header><section className="confirm-box"><span className="confirm-icon"><Check size={30} /></span><span className="quiz-eyebrow">Booking berhasil dibuat</span><h1>Sesi privatmu siap<br />menunggu konfirmasi.</h1><p>Psikolog hanya akan melihat alias dan informasi sesi yang diperlukan.</p><dl><dt>Alias</dt><dd>{confirmed.alias}</dd><dt>Psikolog</dt><dd>{confirmed.psychologist}</dd><dt>Jadwal</dt><dd>{confirmed.slot}</dd><dt>Mode</dt><dd>{confirmed.mode}</dd><dt>Status</dt><dd><b>{confirmed.status}</b></dd></dl><a href="#beranda" className="quiz-next">Kembali ke beranda</a></section></main>
  return <main className="counsel-page"><header className="quiz-topbar"><a className="brand" href="#beranda"><span className="brand-mark"><ShieldCheck size={22} /></span><span>Aegis</span></a><span className="quiz-private"><LockKeyhole size={14} /> Sesi semi-anonim</span></header><section className="counsel-shell"><a className="back-link" href="#beranda"><ArrowLeft size={17} /> Kembali ke beranda</a><div className="counsel-heading"><span className="quiz-eyebrow">Konseling privat Surabaya</span><h1>Temukan pendamping<br />yang tepat untukmu.</h1><p>Di mata psikolog, kamu dikenal sebagai <b>{alias || 'Keluarga-...'}</b>—bukan nama asli. Identitas dan kontakmu tidak ditampilkan pada psikolog.</p></div><div className="privacy-strip"><LockKeyhole size={19} /><span><b>Privasi semi-anonim:</b> psikolog melihat Alias ID dan kebutuhan sesi; data identitas berada di sisi server demo dalam bentuk terenkripsi.</span></div><div className="counsel-grid"><section className="psych-list"><h2>Pilih psikolog</h2>{psychologists.map((p) => <button className={`psych-card ${selected?.id === p.id ? 'selected' : ''}`} key={p.id} onClick={() => choose(p)}><span className="avatar">{p.initials}</span><span><b>{p.name}</b><small>{p.specialty}</small><small><MapPin size={12} /> {p.place} · {p.mode}</small></span><ChevronRight size={17} /></button>)}</section><section className="booking-panel">{!selected ? <div className="booking-empty"><CalendarDays size={30} /><h2>Pilih psikolog dahulu</h2><p>Setelah itu, pilih jadwal yang paling nyaman untukmu.</p></div> : <><div className="selected-psych"><span className="avatar">{selected.initials}</span><div><b>{selected.name}</b><small><Star size={12} fill="currentColor" /> {selected.rating} · {selected.fee}</small></div></div><h2>Atur sesi privat</h2><label>Mode konsultasi</label><div className="choice-row">{(selected.mode === 'Hybrid' ? ['Online', 'Tatap muka'] : [selected.mode]).map((x) => <button className={mode === x ? 'picked' : ''} onClick={() => setMode(x)} key={x}><Video size={15} /> {x}</button>)}</div><label>Pilih jadwal tersedia</label><div className="slot-list">{selected.slots.map((x) => <button className={slot === x ? 'picked' : ''} onClick={() => setSlot(x)} key={x}>{x}</button>)}</div><label>Kebutuhan singkat <small>(opsional)</small></label><textarea value={note} onChange={(e) => setNote(e.target.value)} placeholder="Contoh: ingin membahas stres sekolah…" /><button className="quiz-next" disabled={!slot || !mode} onClick={book}>Konfirmasi booking <Check size={17} /></button></>}</section></div></section></main>
}
