-- Aegis MySQL Schema
-- Target: MySQL 8.0+ / MariaDB 10.6+
-- Import: mysql -u USER -p < database/aegis_schema.sql
--
-- SECURITY NOTE
-- Passwords must be bcrypt/argon2 hashes created by the backend.
-- Encrypt sensitive PII (legal name, phone, emergency contact) in the backend
-- before INSERT. Do not rely on this demo schema alone as production security.

-- Shared hosting note:
-- Create the database in your hosting control panel first, then SELECT that
-- database in phpMyAdmin before importing this file. Shared hosting accounts
-- commonly reject CREATE DATABASE statements.

-- Login account. Do not place real name, address, or emergency details here.
CREATE TABLE users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  email VARCHAR(254) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('client', 'psychologist', 'admin') NOT NULL DEFAULT 'client',
  email_verified_at DATETIME NULL,
  last_login_at DATETIME NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_users_email (email),
  KEY idx_users_role (role)
) ENGINE=InnoDB;

-- Semi-anonymous identifier shown to psychologists and in client-facing sessions.
CREATE TABLE user_aliases (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  alias_code VARCHAR(32) NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_alias_code (alias_code),
  UNIQUE KEY uq_alias_user (user_id),
  CONSTRAINT fk_alias_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Separate PII table. Values ending in _encrypted are ciphertext generated by backend.
CREATE TABLE user_pii (
  user_id BIGINT UNSIGNED NOT NULL,
  display_name_encrypted TEXT NULL,
  legal_name_encrypted TEXT NULL,
  phone_encrypted TEXT NULL,
  address_encrypted TEXT NULL,
  emergency_contact_name_encrypted TEXT NULL,
  emergency_contact_phone_encrypted TEXT NULL,
  encryption_key_version VARCHAR(32) NOT NULL DEFAULT 'v1',
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id),
  CONSTRAINT fk_pii_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Screening responses. category is a product-level indicator, not a diagnosis.
CREATE TABLE screenings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  total_score SMALLINT UNSIGNED NOT NULL,
  stress_category ENUM('ringan', 'sedang', 'tinggi') NOT NULL,
  answers_json JSON NOT NULL,
  consent_share_with_psychologist BOOLEAN NOT NULL DEFAULT FALSE,
  completed_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_screening_user_date (user_id, completed_at),
  KEY idx_screening_category (stress_category),
  CONSTRAINT fk_screening_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT chk_screening_score CHECK (total_score BETWEEN 0 AND 120)
) ENGINE=InnoDB;

CREATE TABLE daily_module_progress (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  module_category ENUM('ringan', 'sedang', 'tinggi', 'dasar') NOT NULL,
  day_number TINYINT UNSIGNED NOT NULL,
  completed_at DATETIME NULL,
  reflection_encrypted TEXT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_module_day (user_id, module_category, day_number),
  CONSTRAINT fk_module_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT chk_module_day CHECK (day_number BETWEEN 1 AND 31)
) ENGINE=InnoDB;

-- Chat data is sensitive; message_encrypted must be encrypted by backend.
CREATE TABLE ai_chat_sessions (
  id CHAR(36) NOT NULL,
  user_id BIGINT UNSIGNED NOT NULL,
  screening_id BIGINT UNSIGNED NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_chat_session_user (user_id, updated_at),
  CONSTRAINT fk_chat_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_chat_screening FOREIGN KEY (screening_id) REFERENCES screenings(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE ai_chat_messages (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  session_id CHAR(36) NOT NULL,
  sender ENUM('user', 'assistant', 'system') NOT NULL,
  message_encrypted MEDIUMTEXT NOT NULL,
  safety_flag BOOLEAN NOT NULL DEFAULT FALSE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_chat_message_session (session_id, created_at),
  CONSTRAINT fk_message_session FOREIGN KEY (session_id) REFERENCES ai_chat_sessions(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Psychologist directory. Psychologist accounts use role='psychologist' in users.
CREATE TABLE psychologist_profiles (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NULL,
  public_name VARCHAR(150) NOT NULL,
  license_number VARCHAR(100) NULL,
  specialties JSON NOT NULL,
  city VARCHAR(80) NOT NULL DEFAULT 'Surabaya',
  consultation_mode SET('online', 'tatap_muka') NOT NULL,
  fee_amount DECIMAL(12,2) NOT NULL,
  rating DECIMAL(2,1) NULL,
  bio TEXT NULL,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_psychologist_user (user_id),
  KEY idx_psychologist_city_active (city, active),
  CONSTRAINT fk_psychologist_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

CREATE TABLE psychologist_slots (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  psychologist_id BIGINT UNSIGNED NOT NULL,
  starts_at DATETIME NOT NULL,
  ends_at DATETIME NOT NULL,
  mode ENUM('online', 'tatap_muka') NOT NULL,
  slot_status ENUM('available', 'held', 'booked', 'cancelled') NOT NULL DEFAULT 'available',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uq_psychologist_slot (psychologist_id, starts_at),
  KEY idx_slot_search (starts_at, slot_status),
  CONSTRAINT fk_slot_psychologist FOREIGN KEY (psychologist_id) REFERENCES psychologist_profiles(id) ON DELETE CASCADE,
  CONSTRAINT chk_slot_time CHECK (ends_at > starts_at)
) ENGINE=InnoDB;

-- Psychologists must query alias, not PII. Store PII nowhere in this table.
CREATE TABLE counseling_bookings (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  psychologist_id BIGINT UNSIGNED NOT NULL,
  slot_id BIGINT UNSIGNED NULL,
  alias_snapshot VARCHAR(32) NOT NULL,
  session_mode ENUM('online', 'tatap_muka') NOT NULL,
  client_note_encrypted TEXT NULL,
  booking_status ENUM('pending', 'confirmed', 'completed', 'cancelled') NOT NULL DEFAULT 'pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_booking_client (user_id, created_at),
  KEY idx_booking_psychologist (psychologist_id, booking_status),
  CONSTRAINT fk_booking_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_booking_psychologist FOREIGN KEY (psychologist_id) REFERENCES psychologist_profiles(id) ON DELETE RESTRICT,
  CONSTRAINT fk_booking_slot FOREIGN KEY (slot_id) REFERENCES psychologist_slots(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Emergency events do not disclose PII automatically; all action is auditable.
CREATE TABLE emergency_events (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id BIGINT UNSIGNED NOT NULL,
  source ENUM('ai', 'psychologist', 'admin', 'user_report') NOT NULL,
  severity ENUM('low', 'medium', 'high', 'critical') NOT NULL,
  reason_encrypted TEXT NOT NULL,
  event_status ENUM('open', 'reviewing', 'resolved', 'false_positive') NOT NULL DEFAULT 'open',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  resolved_at DATETIME NULL,
  PRIMARY KEY (id),
  KEY idx_emergency_status (event_status, severity, created_at),
  CONSTRAINT fk_emergency_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
) ENGINE=InnoDB;

-- Immutable-style access log. Write from backend whenever privileged access happens.
CREATE TABLE audit_logs (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  actor_user_id BIGINT UNSIGNED NULL,
  action VARCHAR(120) NOT NULL,
  target_type VARCHAR(80) NOT NULL,
  target_id VARCHAR(80) NULL,
  reason VARCHAR(500) NULL,
  metadata JSON NULL,
  ip_hash VARCHAR(128) NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  KEY idx_audit_target (target_type, target_id, created_at),
  KEY idx_audit_actor (actor_user_id, created_at),
  CONSTRAINT fk_audit_actor FOREIGN KEY (actor_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB;

-- Demo psychologist directory data. Replace with verified providers before production.
INSERT INTO psychologist_profiles (public_name, specialties, city, consultation_mode, fee_amount, rating, bio) VALUES
('Dr. Ratna Prameswari, M.Psi., Psikolog', JSON_ARRAY('Stres remaja', 'Komunikasi keluarga'), 'Surabaya', 'online,tatap_muka', 180000, 4.9, 'Profil demo — verifikasi kredensial diperlukan.'),
('Nadia Wijaya, M.Psi., Psikolog', JSON_ARRAY('Kecemasan', 'Regulasi emosi'), 'Surabaya', 'online', 160000, 4.8, 'Profil demo — verifikasi kredensial diperlukan.'),
('Arif Rahman, M.Psi., Psikolog', JSON_ARRAY('Perkembangan remaja', 'Sekolah'), 'Surabaya', 'tatap_muka', 200000, 4.9, 'Profil demo — verifikasi kredensial diperlukan.'),
('Dina Kurniawati, M.Psi., Psikolog', JSON_ARRAY('Relasi keluarga', 'Burnout'), 'Surabaya', 'online,tatap_muka', 175000, 4.7, 'Profil demo — verifikasi kredensial diperlukan.');
