import { ArrowLeft, Check, LockKeyhole, Mail, ShieldCheck, UserRound } from 'lucide-react'
import { useState } from 'react'

function makeAlias() { return `Keluarga-A${Math.floor(100 + Math.random() * 900)}` }
export default function AuthPage({ mode }) {
  const isLogin = mode === 'login'; const [name, setName] = useState(''); const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('')
  function submit(event) { event.preventDefault(); const users = JSON.parse(localStorage.getItem('aegis-users') || '[]'); if (isLogin) { const user = users.find((x) => x.email.toLowerCase() === email.toLowerCase() && x.password === password); if (!user) return setError('Email atau kata sandi belum sesuai.'); localStorage.setItem('aegis-session', JSON.stringify({ name: user.name, email: user.email, alias: user.alias })); localStorage.setItem('aegis-user-alias', user.alias); window.location.hash = 'beranda' } else { if (name.trim().length < 2) return setError('Masukkan nama panggilan minimal 2 karakter.'); if (!/^\S+@\S+\.\S+$/.test(email)) return setError('Masukkan alamat email yang valid.'); if (password.length < 6) return setError('Kata sandi minimal 6 karakter.'); if (users.some((x) => x.email.toLowerCase() === email.toLowerCase())) return setError('Email ini sudah terdaftar. Silakan masuk.'); const user = { name: name.trim(), email: email.trim(), password, alias: makeAlias() }; localStorage.setItem('aegis-users', JSON.stringify([...users, user])); localStorage.setItem('aegis-session', JSON.stringify({ name: user.name, email: user.email, alias: user.alias })); localStorage.setItem('aegis-user-alias', user.alias); window.location.hash = 'beranda' } }
  return <main className="auth-page"><header className="quiz-topbar"><a className="brand" href="#beranda"><span className="brand-mark"><ShieldCheck size={22} /></span><span>Aegis</span></a><a href="#beranda" className="back-link"><ArrowLeft size={16} /> Beranda</a></header><section className="auth-layout"><div className="auth-intro"><span className="quiz-eyebrow"><ShieldCheck size={16} /> Ruang aman untuk keluarga</span><h1>Mulai dengan<br /><em>rasa aman.</em></h1><p>Akun Aegis membantu menyimpan progres latihan, alias konseling, dan pengaturanmu pada perangkat ini.</p><ul><li><Check size={16} /> Alias dibuat untuk menjaga privasi sesi.</li><li><Check size={16} /> Tidak ada profil publik.</li><li><Check size={16} /> Kamu tetap dapat memakai fitur tanpa skrining.</li></ul></div><form className="auth-card" onSubmit={submit}><span className="auth-icon">{isLogin ? <LockKeyhole size={25} /> : <UserRound size={25} />}</span><h2>{isLogin ? 'Selamat datang kembali' : 'Buat akun Aegis'}</h2><p>{isLogin ? 'Masuk untuk melanjutkan ruang dukunganmu.' : 'Daftar untuk menyimpan progres demo pada perangkat ini.'}</p>{!isLogin && <label>Nama panggilan<input value={name} onChange={(e) => setName(e.target.value)} placeholder="Contoh: Ibu Rani" /></label>}<label>Email<input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="nama@email.com" /></label><label>Kata sandi<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} placeholder="Minimal 6 karakter" /></label>{error && <div className="auth-error">{error}</div>}<button className="quiz-next">{isLogin ? 'Masuk ke Aegis' : 'Buat akun & lanjutkan'}</button><p className="auth-switch">{isLogin ? 'Belum punya akun?' : 'Sudah punya akun?'} <a href={isLogin ? '#register' : '#login'}>{isLogin ? 'Daftar sekarang' : 'Masuk'}</a></p><small className="auth-demo">Demo lokal: data akun tersimpan di browser ini, bukan server produksi.</small></form></section></main>
}
