import { ArrowLeft, ArrowRight, Bot, BookOpen, CalendarDays, Check, Clock3, HeartHandshake, LockKeyhole, ShieldCheck } from 'lucide-react'

const content = {
  skrining: { icon: Clock3, eyebrow: 'Skrining stres digital', title: 'Pahami sinyal stres secara perlahan.', description: 'Kuesioner 40 pertanyaan ini membantu kamu melihat pola emosi, energi, tidur, dan tekanan harian. Jawabanmu menghasilkan gambaran awal, bukan diagnosis medis.', steps: ['Jawab 40 pertanyaan dengan ritmemu sendiri.', 'Lihat skor dan kategori Ringan, Sedang, atau Tinggi.', 'Terima rekomendasi langkah kecil yang sesuai.'], exampleLabel: 'Contoh output', example: 'Tingkat stres: Sedang — ada beberapa beban yang patut diperhatikan. Coba mulai dengan latihan harian atau bicara dengan orang tepercaya.', button: 'Mulai skrining sekarang', target: '#skrining' },
  ai: { icon: Bot, eyebrow: 'AI Assistant 24/7', title: 'Ruang awal untuk bercerita tanpa dihakimi.', description: 'Aegis AI membantu kamu menamai perasaan, mencoba latihan penenang, dan menemukan langkah berikutnya. AI ini bukan psikolog atau psikiater.', steps: ['Tulis apa yang sedang terasa berat.', 'Pilih prompt bantuan atau mulai percakapan sendiri.', 'Dapatkan respons empatik dan saran langkah kecil.'], exampleLabel: 'Contoh percakapan', example: '“Aku lagi merasa kewalahan.” → “Kedengarannya kamu membawa cukup banyak beban. Kita boleh mulai dari satu napas perlahan.”', button: 'Buka AI Assistant', target: '#ai-chat' },
  modul: { icon: BookOpen, eyebrow: 'Panduan rumahan', title: 'Latihan singkat untuk hari yang terasa berat.', description: 'Modul berisi latihan napas, grounding, refleksi, komunikasi, dan rencana dukungan. Kamu bisa memulai tanpa menyelesaikan skrining.', steps: ['Pilih latihan yang sesuai dengan kebutuhanmu hari ini.', 'Ikuti instruksi dalam 3–10 menit.', 'Tandai selesai dan tulis refleksi bila ingin.'], exampleLabel: 'Contoh latihan', example: 'Napas 4–6: tarik napas selama 4 hitungan, lalu hembuskan selama 6 hitungan. Ulangi perlahan 5 kali.', button: 'Buka latihan harian', target: '#modul' },
  konseling: { icon: CalendarDays, eyebrow: 'Konseling privat', title: 'Terhubung dengan psikolog tanpa membuka identitas.', description: 'Pilih psikolog lokal Surabaya, jadwal, dan mode sesi. Sistem membuat Alias ID agar psikolog tidak melihat nama atau kontak pribadi kamu.', steps: ['Pilih psikolog dan mode online atau tatap muka.', 'Pilih slot jadwal yang tersedia.', 'Konfirmasi booking dengan Alias ID.'], exampleLabel: 'Contoh output', example: 'Booking dibuat untuk Keluarga-A123 · Rabu, 19.00 · Online · Status: Menunggu konfirmasi.', button: 'Lihat psikolog & jadwal', target: '#konseling' },
}

export default function FeatureOverview({ type }) { const item = content[type] || content.skrining; const Icon = item.icon; return <main className="feature-page"><header className="quiz-topbar"><a className="brand" href="#beranda"><span className="brand-mark"><ShieldCheck size={22} /></span><span>Aegis</span></a><span className="quiz-private"><LockKeyhole size={14} /> Aman &amp; privat</span></header><section className="feature-shell"><a className="back-link" href="#dashboard"><ArrowLeft size={17} /> Kembali ke Dashboard</a><div className="feature-hero"><span className="overview-icon"><Icon size={30} /></span><div><span className="quiz-eyebrow">{item.eyebrow}</span><h1>{item.title}</h1><p>{item.description}</p></div></div><div className="overview-grid"><article><h2>Yang akan kamu lakukan</h2><ol>{item.steps.map((step, index) => <li key={step}><span>{index + 1}</span>{step}</li>)}</ol></article><article className="output-card"><span>{item.exampleLabel}</span><p>“{item.example}”</p></article></div><div className="overview-note"><Check size={18} /><span>Kamu dapat berhenti kapan pun. Tidak ada jawaban yang salah, dan Aegis bukan pengganti diagnosis atau layanan darurat.</span></div><a className="primary-button overview-cta" href={item.target}>{item.button} <ArrowRight size={18} /></a></section></main> }
